### ISSUE TITLE
Enforce Email Validation for New Users

### ISSUE THREAD

**Issue by mcsearchin** [smartcitiesdata/react_discovery_ui#104]
As a System Administrator
I want to verify that users of the system own their emails
So that I can better monitor those who gain access to the system

ACs:
- When a user signs up for a new account they should not be tracked by Discovery until they have verified their email address.  Only then will the user become visible to a system administrator, at which point the sys admin will be able to associate the user with an organization.
- Once the email has been verified, the user can log in again, and only then will system be notified that the user has logged in (via the `/logged-in` API)
- Verify the user experience with @jakeclark for a user who has created an account, but has not yet verified the email

Tech Notes:
- Add an Auth0 rule to 'Force' email verification https://auth0.com/rules/email-verified
- This *should* only apply to auth0 owned accounts.  Google accounts shouldn't have to go through this.

Amigos: 
@mcsearchin , @jakeclark

**Comment by jakeclark** [comment]
Verbiage: "You must verify your email before you can save workspaces. Please check your email for the verification link."
