### ISSUE TITLE
Handle Unexpected Auth0 Authentication Errors

### ISSUE THREAD

**Issue by mcsearchin** [smartcitiesdata/react_discovery_ui#122]
As a Discovery UI user
I want to be notified when login fails
So that I know why I cannot see my data

Currently it's possible for unforeseen errors to occur after a successful redirect from an auth0 login.  We should present some message to the user to make them aware that they are not logged in.

ACs:
- Display a message to the user that login failed when it fails.

Talk with @jakeclark about how this should look.  He suggested a flash-style header message bar that could be shown after failed login.

Tech Notes:
- This should happen if the `handleRedirectCallback` fails or the if the called to Discovery API's `logged-in` fails.

Amigos:
@mcsearchin , @jakeclark , @carriebrinkley

**Comment by rajones-hntb** [comment]
we need to write a card to log auth0 error message so we can start to understand what issues users are actually having.
