### ISSUE TITLE
Reference dataset/datasets on the visualizationView page

### ISSUE THREAD

**Issue by kcarra** [smartcitiesdata/react_discovery_ui#143]
We should give the user the ability to navigate to the dataset/datasets that they used to create their saved visualization on the visualizationView page. Currently the user has no way to know what dataset/datasets they used at the time of creating the saved visulization. 

AC:
- [ ] As a logged in user with saved visualizations, when I click on a saved visualization and land on the visualizationView page I should see a reference/links to the datasets that I used to create the visualization
- [ ] When I click on the dataset link I should be redirected back to the datasetview page of that dataset

UX Notes:
- [ ] Clicking on dataset link will open dataset in new tab

TN: 
@jakeclark to provide comps - will tie in with related datasets

Amigos:
@jakeclark , @JarredOlson , @carriebrinkley 

![view-datasets-queries](https://user-images.githubusercontent.com/430082/85753733-804ee000-b6da-11ea-8beb-5ca46181c037.png)

**Comment by ManApart** [comment]
Can we not do a light interrogation of the sql and just build links based on data names? That sounds like the same or less amount of work for something that's more dynamic (as they write queries etc).

**Comment by LtChae** [comment]
Split card to an API card as well, blocking this.
