### ISSUE TITLE
save popover is misaligned

### ISSUE THREAD

**Issue by dunson062786** [smartcitiesdata/react_discovery_ui#157]
When I click on the save button on the write sql page the popover is an 50px down and to the left.
<img width="1620" alt="Screen Shot 2020-01-16 at 3 33 58 PM" src="https://user-images.githubusercontent.com/1486284/72560854-e4d95980-3875-11ea-98b9-731988ec2ca4.png">

**Comment by ManApart** [comment]
Is this a bug or is it intentional?

**Comment by carriebrinkley** [comment]
@jakeclark is this a problem/do you want for it to be fixed?

**Comment by carriebrinkley** [comment]
After talking to Jake, this is not a problem that we are worrying about at this stage in our build.
