### ISSUE TITLE
Data Dictionary Cannot Handle Hierarchical Data 

### ISSUE THREAD

**Issue by NathanielScottStevens** [smartcitiesdata/react_discovery_ui#73]
Clicking the show subschema toggle should not crash the app.

Steps to Reproduce:
* Go to [Cota Realtime Data details page](https://discovery.smartcolumbusos.com/dataset/central_ohio_transit_authority/cota_stream)
* Expand 'Data Dictionary'
* Click left expand toggle on 'vehicle'
* App will crash to a white screen

AC:
* Don't crash - handle the situation gracefully
(Supporting hierarchical data should be a future story card)

Tech Notes:
* Part (or all) of the issue is that Discovery API is not return sub schemas.

**Comment by rob-h-m** [comment]
@NathanielScottStevens @carriebrinkley Help me understand, what "love" is needed to move this card along? Thanks
