### ISSUE TITLE
Load chart information with visualization

### ISSUE THREAD

**Issue by cameronmarsh** [smartcitiesdata/react_discovery_ui#94]
I would like to be able to see plotly chart changes rendered with loaded visualizations

AC:
- [x] When a visualization is loaded, the chart visualization's `dataSources` is populated by executing the `query` of the saved visualization and the chart is redrawn with the loaded data/layout/frame
- [x] The plot is rendered the same way every time the visualization URL is loaded with fresh data
- [x] Assuming the user can save failed/faulty queries, the chart configuration should be standardized before sending to plotly so it doesn't blow up

TN:
- all information regarding plot configuration should be stored in postgres by the `data`, `layout`, and `frames` parts of a saved visualization
- see spike https://github.com/SmartColumbusOS/discovery_ui/issues/21
- blocked by #93 
- Check this in all different browsers (Chrome, Edge, Firefox)

Amigos @cameronmarsh @rajones-hntb @mcsearchin @LtChae

**Comment by LtChae** [comment]
If we're saving the data as part of the visualization, should we prevent the query from re-running on load?

**Comment by cameronmarsh** [comment]
> If we're saving the data as part of the visualization, should we prevent the query from re-running on load?

Card has been updated, so this shouldn't be a concern now

**Comment by LtChae** [comment]
lgtm

**Comment by mcsearchin** [comment]
RE: chart load failures - we've erred on the side of just defaulting things to what Plotly wants at a root level. Basically, Plotly doesn't expose much validation we can take advantage of - Ben
